image: docker:latest

variables:
  IMAGE_NAME: "chanleon/chanleon-official-website"

stages:
  - build

before_script:
  - docker -v

build:
  stage: build
  only:
    - tags
  script:
    - docker build -t $IMAGE_NAME:t-$CI_BUILD_ID .
    - docker tag $IMAGE_NAME:t-$CI_BUILD_ID $CI_REGISTRY/$IMAGE_NAME:$CI_BUILD_TAG
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWD $CI_REGISTRY
    - docker push $CI_REGISTRY/$IMAGE_NAME:$CI_BUILD_TAG